# application.yml
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/vaccination_portal
      database: vaccination_portal
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080
  servlet:
    context-path: /api

jwt:
  secret: your-secret-key-here
  expiration: 86400000 # 24 hours

logging:
  level:
    com.school.vaccination: DEBUG
    org.springframework.data.mongodb: INFO
    org.springframework.security: INFO